config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :auctions
  resources :lots
  resources :bids
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
# frozen_string_literal: true

class Auction < ApplicationRecord
end

app/models/bid.rb
# frozen_string_literal: true

class Bid < ApplicationRecord
  belongs_to :lot

  validates :amount, numericality: {
    greater_than: 0,
    message: 'The bid amount must be greater than 0.'
  }

  validate :amount_greater_than_or_equal_to_required_increment

  def amount_greater_than_or_equal_to_required_increment
    errors.add(:amount, 'Bid is not high enough.') if amount < lot.current_high_bid + lot.bid_increment
  end
end

app/models/lot.rb
# frozen_string_literal: true

class Lot < ApplicationRecord
  has_many :bids

  # The opening bid is special: the 'house' always places the opening bid.
  validates :starting_bid_amount, numericality: {
    greater_than_or_equal_to: 0,
    message: 'The starting bid amount must be greater than 0.'
  }

  serialize :minimum_bid_increment_schedule
  
  validate :increment_schedule_validation

  def bid_increment
    minimum_bid_increment_schedule[0]
  end

  def current_high_bid
    return starting_bid_amount if bids.empty?
    bids.map { |bid| bid.amount }.sort.first
  end

  def increment_schedule_validation
    minimum_bid_increment_schedule.each_value do |increment|
      errors.add(:minimum_bid_increment_schedule, 'Minimum bid increments must be greater than 0.') if increment <= 0
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/auctions_controller.rb
# frozen_string_literal: true

class AuctionsController < ApplicationController
  before_action :set_auction, only: %i[show edit update destroy]

  # GET /auctions or /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1 or /auctions/1.json
  def show; end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit; end

  # POST /auctions or /auctions.json
  def create
    @auction = Auction.new(auction_params)

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1 or /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1 or /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_auction
    @auction = Auction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def auction_params
    params.require(:auction).permit(:name)
  end
end

app/controllers/bids_controller.rb
# frozen_string_literal: true

class BidsController < ApplicationController
  before_action :set_bid, only: %i[show edit update destroy]

  # GET /bids or /bids.json
  def index
    @bids = Bid.all
  end

  # GET /bids/1 or /bids/1.json
  def show; end

  # GET /bids/new
  def new
    @bid = Bid.new
  end

  # GET /bids/1/edit
  def edit; end

  # POST /bids or /bids.json
  def create
    @bid = Bid.new(bid_params)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render :show, status: :created, location: @bid }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bids/1 or /bids/1.json
  def update
    respond_to do |format|
      if @bid.update(bid_params)
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1 or /bids/1.json
  def destroy
    @bid.destroy
    respond_to do |format|
      format.html { redirect_to bids_url, notice: 'Bid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bid
    @bid = Bid.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bid_params
    params.require(:bid).permit(:amount)
  end
end

app/controllers/lots_controller.rb
# frozen_string_literal: true

class LotsController < ApplicationController
  before_action :set_lot, only: %i[show edit update destroy]

  # GET /lots or /lots.json
  def index
    @lots = Lot.all
  end

  # GET /lots/1 or /lots/1.json
  def show; end

  # GET /lots/new
  def new
    @lot = Lot.new
  end

  # GET /lots/1/edit
  def edit; end

  # POST /lots or /lots.json
  def create
    @lot = Lot.new(lot_params)

    respond_to do |format|
      if @lot.save
        format.html { redirect_to @lot, notice: 'Lot was successfully created.' }
        format.json { render :show, status: :created, location: @lot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lots/1 or /lots/1.json
  def update
    respond_to do |format|
      if @lot.update(lot_params)
        format.html { redirect_to @lot, notice: 'Lot was successfully updated.' }
        format.json { render :show, status: :ok, location: @lot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lots/1 or /lots/1.json
  def destroy
    @lot.destroy
    respond_to do |format|
      format.html { redirect_to lots_url, notice: 'Lot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lot
    @lot = Lot.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lot_params
    params.require(:lot).permit(:imageUrl, :description, :name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/auctions_helper.rb
# frozen_string_literal: true

module AuctionsHelper
end

app/helpers/bids_helper.rb
# frozen_string_literal: true

module BidsHelper
end

app/helpers/lots_helper.rb
# frozen_string_literal: true

module LotsHelper
end

app/views/auctions/_form.html.erb
<%= form_with(model: auction) do |form| %>
  <% if auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
        <% auction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auctions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.name %></td>
        <td><%= link_to 'Show', auction %></td>
        <td><%= link_to 'Edit', edit_auction_path(auction) %></td>
        <td><%= link_to 'Destroy', auction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auction', new_auction_path %>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @auction.name %>
</p>

<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>

app/views/bids/_form.html.erb
<%= form_with(model: bid) do |form| %>
  <% if bid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bid.errors.count, "error") %> prohibited this bid from being saved:</h2>

      <ul>
        <% bid.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bids</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.amount %></td>
        <td><%= link_to 'Show', bid %></td>
        <td><%= link_to 'Edit', edit_bid_path(bid) %></td>
        <td><%= link_to 'Destroy', bid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<h1>New Bid</h1>

<%= render 'form', bid: @bid %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @bid.amount %>
</p>

<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionServerRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lots/_form.html.erb
<%= form_with(model: lot) do |form| %>
  <% if lot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lot.errors.count, "error") %> prohibited this lot from being saved:</h2>

      <ul>
        <% lot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :imageUrl %>
    <%= form.text_field :imageUrl %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lots/edit.html.erb
<h1>Editing Lot</h1>

<%= render 'form', lot: @lot %>

<%= link_to 'Show', @lot %> |
<%= link_to 'Back', lots_path %>

app/views/lots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lots</h1>

<table>
  <thead>
    <tr>
      <th>Imageurl</th>
      <th>Description</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lots.each do |lot| %>
      <tr>
        <td><%= lot.imageUrl %></td>
        <td><%= lot.description %></td>
        <td><%= lot.name %></td>
        <td><%= link_to 'Show', lot %></td>
        <td><%= link_to 'Edit', edit_lot_path(lot) %></td>
        <td><%= link_to 'Destroy', lot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lot', new_lot_path %>

app/views/lots/new.html.erb
<h1>New Lot</h1>

<%= render 'form', lot: @lot %>

<%= link_to 'Back', lots_path %>

app/views/lots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Imageurl:</strong>
  <%= @lot.imageUrl %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lot.description %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lot.name %>
</p>

<%= link_to 'Edit', edit_lot_path(@lot) %> |
<%= link_to 'Back', lots_path %>